locapp/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.locataire_index, name=''),
    # path('', views.index, name=''),
    path('register', views.register, name='register'),
    path('login', views.my_login, name='login'),
    path('adm-index', views.adm_index, name='adm-index'),
    path('logout', views.logout, name='logout'),
    # path('my-admin', views.my_admin, name='my-admin'),
    # path('dashboard', views.dashboard, name='dashboard'),
    #-------INDEX'S-------
    path('index-1', views.index1, name='index-1'),
    path('index-2', views.index2, name='index-2'),
    path('index-3', views.index3, name='index-3'),
    path('index-0', views.index0, name='index-0'),
    path('gerant-index', views.gerant_index, name='gerant-index'),
    path('appartements-disponibles', views.locataire_index2, name='appartements-disponibles'),
    # ------GERANT-------
    path('all-gerant', views.all_gerant, name='all-gerant'),
    path('add-gerant', views.add_gerant, name='add-gerant'),
    path('edit-gerant/<int:pk>/', views.edit_gerant, name='edit-gerant'),
    path('delete-gerant/<int:pk>', views.delete_gerant, name="delete-gerant"),
    path('gerant-profile', views.gerant_profile, name='gerant-profile'),
    # ----LOCATAIRE-------
    path('all-locataire', views.all_locataire, name='all-locataire'),
    path('add-locataire', views.add_locataire, name='add-locataire'),
    path('edit-locataire/<int:pk>/', views.edit_locataire, name='edit-locataire'),
    path('delete-locataire/<int:pk>', views.delete_locataire, name="delete-locataire"),

    # ----Appartement-------
    path('all-appartement/', views.all_appartement, name='all-appartement'),
    path('add-appartement/', views.add_appartement, name='add-appartement'),
    path('edit-appartement/<int:pk>/', views.edit_appartement, name='edit-appartement'),
    path('delete-appartement/<int:pk>/', views.delete_appartement, name='delete-appartement'),
    path('all-gerant-appartement/', views.appartements_gerant, name='all-gerant-appartement'),
    path('detail-appartement/<int:appartement_id>/', views.detail_appartement, name='detail-appartement'),
    #-----APP PROFILE -------
    path('app-profile', views.app_profile, name='app-profile'),
    #-----Reservation----------
    path('all-reservatio/', views.all_reservation, name='all-reservation'),
    path('edit-reservation/<int:reservation_id>/', views.edit_reservation, name='edit-reservation'),
    path('delete-reservation/<int:reservation_id>/', views.delete_reservation, name='delete-reservation'),
    path('add-reservation/', views.add_reservation, name='add-reservation'),
    path('create-reservation/<int:appartement_id>/', views.create_reservation, name='create-reservation'),
    path('create-reservation-moi/<int:appartement_id>/', views.create_reservation_moi, name='create-reservation-moi'),
    path('reservation-success/<int:reservation_id>/', views.reservation_success, name='reservation-success'),
    path('reservation-moi-success/<int:reservation_id>/', views.reservation_moi_success, name='reservation-moi-success'),
    path('reservations-en-attente/', views.reservations_en_attente, name='reservations-en-attente'),
    path('edit-reservation-statut/<int:reservation_id>/', views.edit_statut_reservation, name='edit-reservation-statut'),
    path('edit-reservation-moi-statut/<int:reservation_id>/', views.edit_statut_reservation_moi, name='edit-reservation-moi-statut'),
    path('locataire-reservation/', views.locataire_reservation, name='locataire-reservation'),
    path('reservation-jour-confirme-detail/<int:reservation_id>/', views.reservation_jour_confirme_detail, name='reservation-jour-confirme-detail'),
    path('reservation-payee-detail/<int:reservation_id>/', views.reservation_payee_detail, name='reservation-payee-detail'),
    path('reservation-moi-confirme-detail/<int:reservation_id>/', views.reservation_moi_confirme_detail, name='reservation-moi-confirme-detail'),
    path('create-payement-bankili/<int:reservation_id>/', views.create_payement_bankili, name='create-payement-bankili'),
    path('create-payement-sedad/<int:reservation_id>/', views.create_payement_sedad, name='create-payement-sedad'),
    path('create-payement-bimbank/<int:reservation_id>/', views.create_payement_bimbank, name='create-payement-bimbank'),
    path('payement-success/', views.payement_success, name='payement-success'),
    path('paiements-en-cours/', views.paiements_en_cours, name='paiements-en-cours'),
    path('paiement/confirmer/<int:paiement_id>/', views.confirmer_paiement, name='confirmer-paiement'),
    path('paiement/refuser/<int:paiement_id>/', views.refuser_paiement, name='refuser-paiement'),
    path('a-propos-de-nous/', views.a_propos_de_nous, name='a-propos-de-nous'),
]

prx/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('locapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

locapp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date 
from django.utils import timezone









# - Classe gerant

class Gerant(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    nomGER =  models.CharField(max_length=100)
    prenomGER =  models.CharField(max_length=100)
    telGER = models.CharField(max_length=8) 
    adresseGER = models.CharField(max_length=50)
    signature = models.ImageField(upload_to='signatures/', blank=True, null=True)
     
    def __str__(self):

            return self.nomGER 



    



# - Classe locateur
class Locataire(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    nomLOC =  models.CharField(max_length=100)
    prenomLOC =  models.CharField(max_length=100)
    telLOC = models.CharField(max_length=8)
    adresse = models.CharField(max_length=50)

    def __str__(self):

            return self.nomLOC 




# # - Classe appartement


class Appartement(models.Model):
    CATEGORIE_CHOICES = [
        ('jour', 'Par Jour'),
        ('mois', 'Par Mois'),
    ]
    nomAP =  models.CharField(max_length=100)
    telAP = models.CharField(max_length=8)
    adresseAP = models.CharField(max_length=50)
    nb_chambres = models.IntegerField()
    nb_salles_bains=models.IntegerField()
    description = models.CharField(max_length=2000)
    Gerant = models.ForeignKey(Gerant, on_delete=models.CASCADE)
    prix = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    image = models.ImageField(upload_to='appartements/', blank=True, null=True)
    image1 = models.ImageField(upload_to='appartements/', blank=True, null=True)
    image2 = models.ImageField(upload_to='appartements/', blank=True, null=True)
    image3 = models.ImageField(upload_to='appartements/', blank=True, null=True)
    categorie = models.CharField(max_length=10, choices=CATEGORIE_CHOICES)
    


    def __str__(self):

            return self.nomAP 
    

    






# - Classe reservation 

class Reservation(models.Model):
    STATUS_CHOICES = [
        ('Paid', 'Payée'),
        ('Pending', 'En attente'),
        ('Canceled', 'Annulée'),
        ('Success', 'Confirmée'),
    ]

    locataire = models.ForeignKey(Locataire, on_delete=models.CASCADE)
    appartement = models.ForeignKey(Appartement, on_delete=models.CASCADE)
    date_debut = models.DateField(default=date.today)
    date_fin = models.DateField(default=date.today)
    statut = models.CharField(max_length=20, choices=STATUS_CHOICES)
    frais = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Réservation {self.id} - {self.locataire.nomLOC} / {self.appartement.nomAP}"
    


class ReservationMoi(models.Model):
    STATUS_CHOICES = [
        ('Pending', 'En attente'),
        ('Confirmed', 'Confirmée'),
        ('Canceled', 'Annulée'),
        ('Completed', 'Terminée'),
    ]

    PAYMENT_METHOD_CHOICES = [
        ('Cash', 'Cash'),
        ('Electronic', 'Électronique'),
    ]

    locataire = models.ForeignKey(Locataire, on_delete=models.CASCADE)
    appartement = models.ForeignKey(Appartement, on_delete=models.CASCADE)
    date_debut = models.DateField(default=date.today)
    jour_payement = models.IntegerField()  # Day of the month for payment
    statut = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Pending')
    frais = models.DecimalField(max_digits=10, decimal_places=2)
    methode_payement = models.CharField(max_length=10, choices=PAYMENT_METHOD_CHOICES)
    signature_locataire = models.ImageField(upload_to='signatures/', blank=True, null=True)
    signature_gerant = models.ImageField(upload_to='signatures/', blank=True, null=True)

    def __str__(self):
        return f"Réservation Moi {self.id} - {self.locataire.nomLOC} / {self.appartement.nomAP}"
# - Classe Paiement 

class Paiement(models.Model):
    STATUT_CHOICES = [
        ('en_cours', 'En cours'),
        ('confirme', 'Confirmé'),
        ('refuse', 'Refusé'),
    ]

    reservation = models.ForeignKey('Reservation', on_delete=models.CASCADE, blank=True, null=True)
    numero_telephone = models.CharField(max_length=15, blank=True, null=True)
    numero_de_transfert = models.CharField(max_length=50, blank=True, null=True)
    capture_ecran = models.ImageField(upload_to='payement_captures/', blank=True, null=True)
    statut = models.CharField(
        max_length=10,
        choices=STATUT_CHOICES,
        default='en_cours',
    )


    def __str__(self):
        return f"Paiement {self.id} pour Réservation {self.reservation.id}"


    

   
   

# # #     # def __str__(self):

# # #     #     return self.first_name + ' ' + self.last_name





















# class Utilisateur(AbstractUser):
#     GERANT = 'gerant'
#     CLIENT = 'client'
#     ROLE_CHOICES = [
#         (GERANT, 'Gérant'),
#         (CLIENT, 'Client'),
#     ]

#     role = models.CharField(max_length=10, choices=ROLE_CHOICES, default=GERANT)
#     # Ajoutez des champs personnalisés ou des méthodes au besoin
    
#     # Définissez les relations avec les groupes et les permissions directement dans la classe du modèle
#     groups = models.ManyToManyField('auth.Group', related_name='groupes_utilisateur', blank=True)
#     user_permissions = models.ManyToManyField('auth.Permission', related_name='permissions_utilisateur', blank=True)

#     class Meta:
#         # Spécifiez le nom de la table pour éviter les problèmes de migration
#         db_table = 'utilisateur'



class Profile(models.Model):
    USER_TYPE_CHOICES = [
        ('admin', 'Admin'),
        ('gerant', 'Gerant'),
        ('locataire', 'Locataire'),
    ]
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=10, choices=USER_TYPE_CHOICES)
    
    def __str__(self):
        return self.user.username

locapp/templates/adm/add-locataire.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Ajouter un locataire </title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{%static 'b/images/ico.png'%}">
    <link rel="stylesheet" href="{%static 'b/vendor/bootstrap-select/dist/css/bootstrap-select.min.css'%}">
    <link rel="stylesheet" href="{%static 'b/css/style.css'%}">
	
	<!-- Pick date -->
    <link rel="stylesheet" href="{%static 'b/vendor/pickadate/themes/default.css'%}">
    <link rel="stylesheet" href="{%static 'b/vendor/pickadate/themes/default.date.css'%}">

</head>

<body>

    <!--Nav header start -->
    {% include "adm/navheader.html" %}



        <!--**********************************
            Sidebar start
        ***********************************-->
        {% include "adm/sidebar.html" %}
        <!--**********************************
            Sidebar end
        ***********************************-->

		
		
        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">
            <!-- row -->
            <div class="container-fluid">
				
				<div class="row page-titles mx-0">
                    <div class="col-sm-6 p-md-0">
                        <div class="welcome-text">
                            <h4>Ajouter un locataire</h4>
                        </div>
                    </div>
                    <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="locapp/dashboard.html">Home</a></li>
                            <li class="breadcrumb-item active"><a href="javascript:void(0);">Locataires</a></li>
                            <li class="breadcrumb-item active"><a href="javascript:void(0);">Ajouter un locataire</a></li>
                        </ol>
                    </div>
                </div>
				
				<div class="row">
					<div class="col-xl-12 col-xxl-12 col-sm-12">
                        <div class="card">
                            <div class="card-header">
								<h5 class="card-title">Infomations basiques</h5>
							</div>
							<div class="card-body">
                                <div class="text-center text-muted mb-4">

                                    {% if msg %}
                                      <small>{{ msg | safe }}</small>
                                    {% else %}
                                      Add your credentials
                                    {% endif %}  
                                  
                                  </div>
                    
                                  {% if not success %}
                                    <form action="#" method="post">
                                        {% csrf_token %}
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group">
                                                    <label class="form-label">First Name </label>
                                                    {{form.first_name}}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group">
                                                    <label class="form-label">Last Name </label>
                                                    {{form.last_name}}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group">
                                                    <label class="form-label">Username </label>
                                                    {{form.username}}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group">
                                                    <label class="form-label">Email </label>
                                                    {{form.email}}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group">
                                                    <label class="form-label">Registration Date</label>
                                                    {{form.date_joined}}
                                                </div>
                                            </div>
                                            
                                            
                                            
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group">
                                                    <label class="form-label">Mobile Number </label>
                                                    {{form.telephone}}
                                                </div>
                                            </div>
                                            
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group">
                                                    <label class="form-label">Password </label>
                                                    {{form.password1}}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group">
                                                    <label class="form-label">Confirm Password </label>
                                                    {{form.password2}}
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-md-6 col-sm-12">
                                                <div class="form-group">
                                                    <label class="form-label">Adresse </label>
                                                    {{form.adresse}}
                                                </div>
                                            </div>
                                            
                                            
                                            <div class="col-lg-12 col-md-12 col-sm-12">
                                                <button type="submit" class="btn btn-primary">Ajouter</button>
                                                <button type="button" class="btn btn-light" onclick="window.history.back()">Annuler</button>
                                            </div>
                                        </div>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
				</div>
                
            </div>
        </div>
        <!--**********************************
            Content body end
        ***********************************-->


        <!--**********************************
            Footer start
        ***********************************-->
		{% include "adm/footer.html" %}
        
        <!--**********************************
            Footer end
        ***********************************-->

		<!--**********************************
           Support ticket button start
        ***********************************-->

        <!--**********************************
           Support ticket button end
        ***********************************-->


    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    <!--**********************************
        Scripts
    ***********************************-->
    <!-- Required vendors -->
<script src="{%static 'b/vendor/global/global.min.js'%}"></script>
	<script src="{%static 'b/vendor/bootstrap-select/dist/js/bootstrap-select.min.js'%}"></script>
    <script src="{%static 'b/js/custom.min.js'%}"></script>
	<script src="{%static 'b/js/dlabnav-init.js'%}"></script>

	<!-- Svganimation scripts -->
    <script src="{%static 'b/vendor/svganimation/vivus.min.js'%}"></script>
    <script src="{%static 'b/vendor/svganimation/svg.animation.js'%}"></script>
    <script src="{%static 'b/js/styleSwitcher.js'%}"></script>
	
	<!-- pickdate -->
    <script src="{%static 'b/vendor/pickadate/picker.js'%}"></script>
    <script src="{%static 'b/vendor/pickadate/picker.time.js'%}"></script>
    <script src="{%static 'b/vendor/pickadate/picker.date.js'%}"></script>
	
	<!-- Pickdate -->
    <script src="{%static 'b/js/plugins-init/pickadate-init.js'%}"></script>
	
</body>
</html>

locapp/templates/adm/all-reservation.html
{% extends "adm/base-index.html" %}

{% block adm %}

<div class="content-body">
    <div class="container-fluid">
                <div class="col-xl-12 col-xxl-12 col-lg-12 col-md-12 col-sm-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Liste des réservations</h4>
                        </div>
                        <div class="card-body">
                            <div class="table-responsive recentOrderTable">
                                <table class="table verticle-middle table-responsive-md">
                                    <thead>
                                        <tr>
                                            <th scope="col">No.</th>
                                            <th scope="col">Nom du locataire</th>
                                            <th scope="col">Nom de l'appartement</th>
                                            <th scope="col">Date début</th>
                                            <th scope="col">Date fin</th>
                                            <th scope="col">Statut</th>
                                            <th scope="col">Frais</th>
                                            <th scope="col">Modifier</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for reservation in reservations %}
                                        <tr>
                                            <td>{{ reservation.id }}</td>
                                            <td>{{ reservation.locataire.nomLOC }}</td>
                                            <td>{{ reservation.appartement.nomAP }}</td>
                                            <td>{{ reservation.date_debut }}</td>
                                            <td>{{ reservation.date_fin }}</td>
                                            <td>
                                                {% if reservation.get_statut_display == 'Payée' %}
                                                <span class="badge badge-rounded badge-success">Payée</span>
                                                {% elif reservation.get_statut_display == 'Annulée' %}
                                                <span class="badge badge-rounded badge-danger">Annulé</span>
                                                {% elif reservation.get_statut_display == 'En attente' %}
                                                <span class="badge badge-rounded badge-warning">En attente</span>
                                                {% else %}
                                                <span class="badge badge-rounded badge-secondary">{{ reservation.get_statut_display }}</span>
                                                {% endif %}
                                            </td>
                                            <td>{{ reservation.frais }}MRU</td>
                                            <td>
                                                <a href="{% url 'edit-reservation' reservation.id %}" class="btn btn-sm btn-primary"><i class="la la-pencil"></i></a>
                                                <a href="{% url 'delete-reservation' reservation.id %}" class="btn btn-sm btn-danger"><i class="la la-trash-o"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
    </div>

</div>

{% endblock %}

locapp/templates/adm/edit-appartement.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Modifier appartement </title>
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{%static 'b/images/ico.png'%}">
    <link rel="stylesheet" href="{%static 'b/vendor/bootstrap-select/dist/css/bootstrap-select.min.css'%}">
	
	<!-- Datatable -->
    <link href="{%static 'b/vendor/datatables/css/jquery.dataTables.min.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="{%static 'b/css/style.css'%}">
</head>

<body>

    {% include "adm/navheader.html" %}
    {% include "adm/sidebar.html" %}

    <div class="content-body">
        <div class="container-fluid">
            <div class="row page-titles mx-0">
                <div class="col-sm-6 p-md-0">
                    <div class="welcome-text">
                        <h4>Modifier Appartement</h4>
                    </div>
                </div>
                <div class="col-sm-6 p-md-0 justify-content-sm-end mt-2 mt-sm-0 d-flex">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'adm-index' %}">Accueil</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0);">Appartements</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0);">Modifier Appartement</a></li>
                    </ol>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_nomAP">Nom de l'appartement</label>
                                    {{ form.nomAP }}
                                </div>
                                <div class="form-group">
                                    <label for="id_telAP">Téléphone</label>
                                    {{ form.telAP }}
                                </div>
                                <div class="form-group">
                                    <label for="id_adresseAP">Adresse</label>
                                    {{ form.adresseAP }}
                                </div>
                                <div class="form-group">
                                    <label for="id_nb_chambres">Nombre de chambres</label>
                                    {{ form.nb_chambres }}
                                </div>
                                <div class="form-group">
                                    <label for="id_nb_salles_bains">Nombre de salle de bains</label>
                                    {{ form.nb_salles_bains }}
                                </div>
                                <div class="form-group">
                                    <label for="id_description">Description</label>
                                    {{ form.description }}
                                </div>
                                <div class="form-group">
                                    <label for="id_Gerant">Proprietaire</label>
                                    {{ form.Gerant }}
                                </div>
                                <div class="form-group">
                                    <label for="id_images">Images</label>
                                    {{ form.image }}
                                </div>
                                <button type="submit" class="btn btn-primary">Enregistrer</button>
                                <button type="button" class="btn btn-light" onclick="window.history.back()">Annuler</button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
</div>
</div>
<!--**********************************
Content body end
***********************************-->


<!--**********************************
Footer start
***********************************-->
<div class="footer">
<div class="copyright">
    <p>Copyright © Designed &amp; Developed by <a href="../index.htm" target="_blank">DexignLab</a> 2020</p>
</div>
</div>
<!--**********************************
Footer end
***********************************-->

<!--**********************************
Support ticket button start
***********************************-->

<!--**********************************
Support ticket button end
***********************************-->


</div>
<!--**********************************
Main wrapper end
***********************************-->

<!--**********************************
Scripts
***********************************-->
<!-- Required vendors -->
<script src="{%static 'b/vendor/global/global.min.js'%}"></script>
<script src="{%static 'b/vendor/bootstrap-select/dist/js/bootstrap-select.min.js'%}"></script>
<script src="{%static 'b/js/custom.min.js'%}"></script>
<script src="{%static 'b/js/dlabnav-init.js'%}"></script>	

<!-- Datatable -->
<script src="{%static 'b/vendor/datatables/js/jquery.dataTables.min.js'%}"></script>
<script src="{%static 'b/js/plugins-init/datatables.init.js'%}"></script>

<!-- Svganimation scripts -->
<script src="{%static 'b/vendor/svganimation/vivus.min.js'%}"></script>
<script src="{%static 'b/vendor/svganimation/svg.animation.js'%}"></script>
<script src="{%static 'b/js/styleSwitcher.js'%}"></script>


</body>
</html>

locapp/templates/adm/edit-reservation.html
{% extends "adm/base-index.html" %}

{% block adm %}


<div class="content-body">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-12 col-xxl-12 col-lg-12 col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Modifier une Réservation</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" autocomplete="off">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Enregistrer</button>
                            <button type="button" class="btn btn-light" onclick="window.history.back()">Annuler</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

locapp/templates/adm/footer.html
<div class="footer">
    <div class="copyright">
        <p>Copyright © Designed &amp; Developed by <a href="../index.htm" target="_blank">Dexignlab</a> 2020</p>
    </div>
</div>